# -*- coding: utf-8 -*-
"""flask_API_cat&dogs_classifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19kqmpD11vWdXted8j4PbvgXFQ9_weLMQ
"""

!pip install flask flask-cors pyngrok tensorflow

!ngrok authtoken 2tIcWKpyc4uhY5BDkK9rTw5Zp4r_3Ha62eCy8Lj5FDQb65ChM

import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np
from flask import Flask, request, jsonify
from flask_cors import CORS
from pyngrok import ngrok
import os

# Inisialisasi Flask
app = Flask(__name__)
CORS(app)  # Tambahkan CORS agar API bisa diakses dari mana saja

# Load model
MODEL_PATH = '/content/cats_vs_dogs_model.h5'  # Ubah nama file sesuai nama model yang di-upload
model = load_model(MODEL_PATH)

# Preprocessing fungsi untuk gambar
def preprocess_image(img_path):
    img = image.load_img(img_path, target_size=(180, 180))  # Sesuaikan dengan model
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array /= 255.0  # Normalisasi
    return img_array

# Endpoint untuk cek API berjalan
@app.route("/", methods=["GET"])
def home():
    return "API untuk Kucing & Anjing Classifier"

# Endpoint untuk prediksi
@app.route("/predict", methods=["POST"])
def predict():
    if "file" not in request.files:
        return jsonify({"error": "No file uploaded"}), 400

    file = request.files["file"]
    file_path = "/content/temp.jpg"
    file.save(file_path)

    # Preprocess image
    img_array = preprocess_image(file_path)

    # Prediksi
    predictions = model.predict(img_array)
    result = "Dog" if predictions[0][0] > 0.5 else "Cat"

    return jsonify({"prediction": result})

# Jalankan Flask dan Ngrok
if __name__ == "__main__":
    # Hapus ngrok session sebelumnya jika ada
    ngrok.kill()

    # Buka koneksi ke ngrok
    public_url = ngrok.connect(5000)
    print(" * ngrok URL:", public_url)

    # Jalankan Flask
    app.run(port=5000)